/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "项目介绍",
    },
    {
      type: "category",
      label: "快速入门",
      items: [
        "quick-start/setup",
        "quick-start/hello-world",
        "quick-start/rsx",
      ],
    },
    {
      type: "category",
      label: "页面设计",
      items: [
        "ui-design/style",
        "ui-design/dyn-content",
        "ui-design/cond-render",
      ]
    },
  ],
};

module.exports = sidebars;
